### ISSUE TITLE
checkScope работает некорректно, если у группы scope с методом

### ISSUE THREAD

**Issue by topor-topor** [bezumkin/vesp-core#5]
Метод контроллера возвращает `failure`, если у группы задан scope на определенный метод.
Hапример, если у группы разрешение `something/get` и запрос методом `GET`, то `Controller` вернет `failure` из-за логики метода `hasScope` модели User (будет сравниваться строка `something` с `something/get` дважды)

https://github.com/bezumkin/vesp-core/blob/5257709e801e62e3d3e2c9429a9aae4e732c21b3/src/Controllers/Controller.php#L92-L97

**Comment by bezumkin** [comment]
@topor-topor Проверь, пожалуйста - теперь должно правильно работать.
